name: deeplearning
channels:
  - menpo
  - conda-forge
  - defaults
dependencies:
  - ipython
  - jupyterlab
  - notebook
  - keras=2.1.5
  - matplotlib
  - numpy
  - opencv
  - pandas
  - pillow
  - pip
  - pyserial
  - python=3.5.5
  - scikit-image
  - scikit-learn
  - scipy
  - tensorflow
  - wheel
  - opencv3